Repository shared-solutions/FE_NEXT, pull requests merged in 2024-02, with the labels that each got.

#21 Feat#18: oauth 수정 및 css 전면수정
  project/app/(afterlogin)/menu/page.jsx
  project/app/(beforelogin)/_component/nickname.jsx
  project/app/(beforelogin)/page.jsx
  project/app/api/auth/[...nextauth]/route.jsx
  project/app/components/footer.jsx
  project/app/components/header.jsx
  project/app/globals.css
  project/app/layout.jsx
  project/app/modules/footer.module.scss
  project/app/modules/header.module.scss
  project/app/modules/homeCss/home.module.scss
  project/app/modules/menuCss/info.module.scss
  project/app/modules/menuCss/menu.module.scss
  project/app/modules/reviewCss/button.module.scss
  project/app/modules/reviewCss/review.module.scss
  project/app/modules/viewdetailCss/viewdetail.module.scss
  project/app/modules/writepostCss/writepost.module.scss
  project/app/modules/writepostCss/writepostfooter.module.scss
  project/app/public/image/f_comment.jsx
  project/app/public/image/f_home.jsx
  project/app/public/image/f_vote.jsx
  project/app/public/image/logo.png
  project/package-lock.json
Labels: feat

#22 Feat#19 투표 불러오기 1차
  project/app/api/auth/[...nextauth]/route.jsx
  project/app/components/votedList/GridViewItem.jsx
  project/app/components/votedList/LineViewItem.jsx
  project/app/components/votedList/VotedModal.jsx
  project/app/components/writereview/WriteReview.jsx
  project/app/modules/writepostCss/writepost.module.scss
  project/app/public/image/close_round.png
Labels: feat

#25 Feat#23 후기 작성 페이지 수정
  project/app/components/writepost/WritePost.jsx
  project/app/components/writereview/WriteReview.jsx
  project/app/components/writereview/WriteReviewFooter.jsx
  project/app/components/writereview/WriteReviewHeader.jsx
  project/app/modules/voteCss/normalvoteitem.module.scss
  project/app/modules/voteCss/votemodal.module.scss
  project/app/modules/votedListCss/gridViewItem.module.scss
  project/app/modules/votedListCss/lineViewItem.module.scss
  project/app/modules/votedListCss/votedmodal.module.scss
  project/app/modules/writepostCss/writepost.module.scss
  project/app/modules/writepostCss/writepostfooter.module.scss
  project/app/modules/writepostCss/writepostheader.module.scss
  project/app/public/image/bar.png
Labels: feat

#32 mainhome hotbox 수정
  project/app/DATA/dummyData.js
  project/app/components/hot/Hot.jsx
  project/app/components/hot/HotBox.jsx
  project/app/modules/hotCss/hotbox.module.scss
  project/app/public/image/hotback.png
Labels: feat

#34 경로처리
  project/app/components/waitinganswer/HomeWriteButtonLay.jsx
  project/app/modules/hotCss/hotbox.module.scss
  project/app/modules/waitCss/writebutton.module.scss
Labels: feat

#37 api연동 댓글 / 홈 화면 / 추천,신고,스크랩 1차
  project/app/api/api/choice.js
  project/app/api/api/comment.js
  project/app/api/api/home.js
  project/app/api/api/index.js
  project/app/api/api/like.js
  project/app/api/api/report.js
  project/app/api/api/scrap.js
  project/package-lock.json
  project/package.json
Labels: api

#53 Feat#47
  project/app/(afterlogin)/vote/page.jsx
  project/app/components/postlist/GeneralPostBox.jsx
  project/app/components/vote/Category.jsx
  project/app/components/vote/VoteDeadline.jsx
  project/app/components/vote/VoteModal.jsx
  project/app/components/vote/VoteStyle.jsx
  project/app/components/writepost/WritePost.jsx
  project/app/components/writepost/WritePostHeader.jsx
  project/app/modules/postListCss/generalPostBox.module.scss
  project/app/modules/postListCss/voteList.module.scss
  project/app/public/image/defaultUserImg.png
  project/app/public/image/pencil.png
  project/app/zustand/voteStore.jsx
  project/package-lock.json
  project/package.json
Labels: feat, api

#55 Feat#51 댓글 채택 연동
  .DS_Store
  project/app/(afterlogin)/vote/page.jsx
  project/app/api/api/choice.js
  project/app/api/api/comment.js
  project/app/api/api/like.js
  project/app/components/comment/CommentBody.jsx
  project/app/components/comment/CommentSort.jsx
  project/app/components/hot/Hot.jsx
  project/app/components/hot/HotBox.jsx
  project/app/components/viewdetail/Detail.jsx
  project/app/modules/commentCss/commentBody.module.scss
  project/app/modules/waitCss/wait.module.scss
  project/app/modules/waitCss/waitbox.module.scss
  project/app/public/image/checkmate.png
  project/app/public/image/cotrash.png
Labels: feat, api

#57 댓글 에러처리
  .DS_Store
  project/app/components/comment/CommentBody.jsx
  project/app/components/comment/CommentSort.jsx
  project/app/components/toast/Toast.jsx
  project/app/modules/commentCss/commentBody.module.scss
  project/app/modules/inputCss/commentInput.module.scss
  project/app/modules/postListCss/generalPostBox.module.scss
  project/app/modules/toastCss/toast.module.scss
  project/app/modules/viewdetailCss/detail.module.scss
  project/app/public/image/selectCheck.png
  project/app/zustand/voteStore.jsx
Labels: feat, api

#124 Feat#117 글 전체보기, 답변 기다리는 고민들, 가장 핫한 - 추가
  project/app/(afterlogin)/vote/page.jsx
  project/app/components/comment/CommentSort.jsx
  project/app/components/hot/HotBox.jsx
  project/app/components/postlist/CardPostBox.jsx
  project/app/components/postlist/GaugePostBox.jsx
  project/app/components/postlist/GeneralPostBox.jsx
  project/app/components/viewdetail/Detail.jsx
  project/app/components/waitinganswer/WaitingAnswer.jsx
  project/app/modules/hotCss/hot.module.scss
  project/app/modules/hotCss/hotbox.module.scss
  project/app/modules/postListCss/cardPostBox.module.scss
  project/app/modules/postListCss/gaugePostBox.module.scss
  project/app/modules/postListCss/generalPostBox.module.scss
  project/app/public/image/check_button.png
Labels: feat, api
